=head1 NAME

package-a - Sample package - a script that prints a message.

=head1 SYNOPSIS

package-a 

=head1 DESCRIPTION

 Sample package - a script that prints a message.

=head1 AUTHORS

B<package-a> was written by Art Crawford <art@a4pizza.com>.

This manual page was written by Art Crawford <art@a4pizza.com>. 
=cut
